{{- /* gotype: morpheus/pkg/fsm-generator.TemplateModel */ -}}
package {{ .Model.Name | snake }}

// Code generated by fsm-generator. YOU SHOULD EDIT THIS FILE

import (
    "context"

    "github.com/inplat/fsm-framework.git/fsm-engine/model"
)

func (s *{{ .State.Name | camel }}StateDeclaration) EventHandler(ctx context.Context, ev *model.Event) model.State {
    {{- if or .State.FailFinal .State.SuccessFinal }}
    return nil
    {{- else}}
    panic("implement {{ .Model.Name | snake }} model {{ .State.Name | snake }} state event handler")
    {{- end}}
}
