// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/inplat/fsm-framework.git/fsm-engine/model"
)

// CallbackManagerMock is an autogenerated mock type for the CallbackManagerMock type
type CallbackManagerMock struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, tx
func (_m *CallbackManagerMock) Send(ctx context.Context, tx model.Tx) {
	_m.Called(ctx, tx)
}

// Stop provides a mock function with given fields:
func (_m *CallbackManagerMock) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
