// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TestServiceMock is an autogenerated mock type for the TestServiceMock type
type TestServiceMock struct {
	mock.Mock
}

// Foo provides a mock function with given fields: s
func (_m *TestServiceMock) Foo(s string) {
	_m.Called(s)
}
