// Code generated by fsm-generator. DO NOT EDIT.
package first

import (
	"time"

	"github.com/inplat/fsm-framework.git/fsm-engine/model"
)

var CreatedState model.State = &CreatedStateDeclaration{}

type CreatedStateDeclaration struct {
}

func (s *CreatedStateDeclaration) Name() string {
	return "FIRST_TX_CREATED"
}

func (s *CreatedStateDeclaration) EventType() string {
	return "first_tx_created_state_event"
}

func (s *CreatedStateDeclaration) Queue() string {
	return "first_tx_created_state_event_queue"
}

func (s *CreatedStateDeclaration) CanTransitIn(state model.State) bool {
	if state == CreatedState {
		return true
	}

	if state == SecondState {
		return true
	}

	if state == DoneState {
		return true
	}

	return false
}

func (s *CreatedStateDeclaration) MaxRetiesCount() int {
	return 3
}

func (s *CreatedStateDeclaration) MinRetiesDelay() time.Duration {
	return 15 * time.Second // 15s
}

func (s *CreatedStateDeclaration) CancellationTTL() time.Duration {
	return 1800 * time.Second // 30m0s
}

func (s *CreatedStateDeclaration) FallbackState() model.State {
	return nil
}

func (s *CreatedStateDeclaration) IsInitial() bool {
	return true
}

func (s *CreatedStateDeclaration) IsSuccessFinal() bool {
	return false
}

func (s *CreatedStateDeclaration) IsFailFinal() bool {
	return false
}

func (s *CreatedStateDeclaration) Model() model.Model {
	return Model
}

func (s *CreatedStateDeclaration) Service() Service {
	return Model.Service().(Service)
}
