package first

// Code generated by fsm-generator. YOU SHOULD EDIT THIS FILE

import (
	"context"

	"github.com/google/uuid"

	"fsm-framework/fsm-engine/model"
)

func (s *CreatedStateDeclaration) EventHandler(ctx context.Context, ev *model.Event) model.State {
	if ev.Tx.ID() == uuid.Nil {
		return DoneState
	}

	return ErrState
}
