package first

// Code generated by fsm-generator. YOU SHOULD EDIT THIS FILE

import (
	"context"

	"github.com/inplat/fsm-framework.git/fsm-engine/model"
)

func (s *DoneStateDeclaration) EventHandler(ctx context.Context, ev *model.Event) model.State {
	return nil
}
