package first

// Code generated by fsm-generator. YOU SHOULD EDIT THIS FILE

import (
	"context"

	"fsm-framework/fsm-engine/model"
)

func (s *ErrStateDeclaration) EventHandler(ctx context.Context, ev *model.Event) model.State {
	return nil
}
