package first

// Code generated by fsm-generator. YOU SHOULD EDIT THIS FILE

import (
	"context"

	"fsm-framework/fsm-engine/model"
)

func (s *SecondStateDeclaration) EventHandler(ctx context.Context, ev *model.Event) model.State {
	err := s.Service().Foo(ev.Tx.CallbackURL())
	if err != nil {
		return ErrState
	}

	return DoneState
}
